### ISSUE TITLE
Main Tasks List

### ISSUE THREAD

**Issue by HamzaEzzRa** [HamzaEzzRa/Titsuite#1]
- [x] Cahier de Charges #3 ----> @hsouf @aminejamai @HamzaEzzRa @Kahlaoui-Ismail
- [x] Diagramme de Cas d'Utilisation #2 ----> @hsouf @aminejamai @HamzaEzzRa @Kahlaoui-Ismail 
- [x] Diagramme de Séquence #4 ----> @hsouf @aminejamai @HamzaEzzRa @Kahlaoui-Ismail
- [x] Diagramme de Classes #5  ----> @hsouf @aminejamai @HamzaEzzRa @Kahlaoui-Ismail
- [ ] Maquettes de l'Utilisateur #7 ----> @aminejamai  @Kahlaoui-Ismail
